# Generated by Django 5.1.2 on 2024-12-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_file', models.FileField(upload_to='Movies')),
                ('movie_poster', models.ImageField(upload_to='Posters')),
                ('director_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=6)),
                ('release_date', models.DateField()),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.genre')),
            ],
        ),
    ]
