# Generated by Django 5.1.2 on 2024-12-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Cast')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.movie')),
            ],
        ),
    ]
