# Generated by Django 5.1.2 on 2025-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
