# Generated by Django 5.1.2 on 2024-12-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_subscription_plan'),
        ('User_App', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.subscription_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_App.viewers')),
            ],
        ),
    ]
