# Generated by Django 5.1.2 on 2025-01-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_movie_dislike_count_movie_like_count'),
        ('User_App', '0003_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_App.viewers')),
            ],
        ),
    ]
