# Generated by Django 5.1.2 on 2025-01-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_like',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
