# Generated by Django 5.1.2 on 2025-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_alter_user_like_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_like',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='user_like',
            name='like',
        ),
        migrations.AddField(
            model_name='user_like',
            name='action',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
