# Generated by Django 5.1.2 on 2025-01-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_remove_user_like_dislike_remove_user_like_like_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_like',
        ),
    ]
