# Generated by Django 5.1.2 on 2025-01-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0009_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewers',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
