# Generated by Django 5.1.2 on 2025-01-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0014_remove_subscription_user_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_user',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
