# Generated by Django 5.1.2 on 2025-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0016_alter_viewers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
