# Generated by Django 5.1.2 on 2025-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0017_alter_viewers_email_alter_viewers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='viewers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
